### ISSUE TITLE
missing gems in the Gemfile

### ISSUE THREAD

**Issue by oren** [ghostandthemachine/sinatra-haml-bootstrap-fluid#2]
I had to add the following to my Gemfile to make it work:
gem "dm-validations"
gem "dm-timestamps"
gem "dm-migrations"
gem "dm-sqlite-adapter"

**Comment by ghostandthemachine** [comment]
they are back in the Gemfile now. I had issues with my dm-core install that I cleaned up and must have accidentally removed them. thanks for the heads up!
